[
    'Antarctica',
    'Bouvet Island',
    'Heard Island and McDonald Islands',
    'United States Minor Outlying Islands',
    'Tokelau',
    'British Indian Ocean Territory',
    'Netherlands Antilles',
    'Serbia and Montenegro',
    'Antigua and Barbuda',
    'Anguilla',
    'American Samoa',
    'Aland Islands',
    'Barbados',
    'Saint Barthelemy',
    'Bermuda',
    'Bonaire, Saint Eustatius and Saba',
    'Cocos Islands',
    'Cook Islands',
    'Christmas Island',
    'Dominica',
    'Falkland Islands',
    'Micronesia',
    'Faroe Islands',
    'Grenada',
    'Guernsey',
    'Gibraltar',
    'Greenland',
    'South Georgia and the South Sandwich Islands',
    'Isle of Man',
    'Jersey',
    'Kiribati',
    'Saint Kitts and Nevis',
    'Liechtenstein',
    'Saint Martin',
    'Marshall Islands',
    'Northern Mariana Islands',
    'Maldives',
    'Norfolk Island',
    'Nauru',
    'Niue',
    'Saint Pierre and Miquelon',
    'Pitcairn',
    'Palau',
    'Solomon Islands',
    'Seychelles',
    'Saint Helena',
    'Svalbard and Jan Mayen',
    'San Marino',
    'Sao Tome and Principe',
    'Sint Maarten',
    'French Southern Territories',
    'Tonga',
    'Tuvalu',
    'Vatican',
    'Vanuatu',
    'Wallis and Futuna',
    'Samoa'
]